kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: sub-dc2
networking:
  podSubnet: "10.40.0.0/16"
  serviceSubnet: "10.41.0.0/16"
nodes:
- role: control-plane
  extraPortMappings:
    # CQL native port — access dc2 Cassandra via localhost:9043
    - containerPort: 30043
      hostPort: 9043
      protocol: TCP
