kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: sub-dc1
networking:
  podSubnet: "10.30.0.0/16"
  serviceSubnet: "10.31.0.0/16"
nodes:
- role: control-plane
  extraPortMappings:
    # CQL native port — access dc1 Cassandra via localhost:9042
    - containerPort: 30042
      hostPort: 9042
      protocol: TCP
    # Internode gossip (for debugging)
    - containerPort: 30070
      hostPort: 7000
      protocol: TCP
